"""add_ap_ingestion_fields

Revision ID: 14a7f3f2e38c
Revises: 0001
Create Date: 2026-08-18 01:51:43.088128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a7f3f2e38c'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Check audio_queue columns
    aq_cols = [c['name'] for c in inspector.get_columns('audio_queue')] if inspector.has_table('audio_queue') else []
    if 'source' not in aq_cols:
        op.add_column('audio_queue', sa.Column('source', sa.String(), nullable=True))
    if 'source_upload_id' not in aq_cols:
        op.add_column('audio_queue', sa.Column('source_upload_id', sa.String(), nullable=True))
    if 'title' not in aq_cols:
        op.add_column('audio_queue', sa.Column('title', sa.String(), nullable=True))
    if 'artist' not in aq_cols:
        op.add_column('audio_queue', sa.Column('artist', sa.String(), nullable=True))
    if 'note' not in aq_cols:
        op.add_column('audio_queue', sa.Column('note', sa.String(), nullable=True))
    
    op.alter_column('audio_queue', 'uploaded_by_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
               
    uq_names = [uq['name'] for uq in inspector.get_unique_constraints('audio_queue')] if inspector.has_table('audio_queue') else []
    if 'uq_source_upload_id' not in uq_names:
        op.create_unique_constraint('uq_source_upload_id', 'audio_queue', ['source', 'source_upload_id'])
        
    sd_cols = [c['name'] for c in inspector.get_columns('supporting_documents')] if inspector.has_table('supporting_documents') else []
    if 'description' not in sd_cols:
        op.add_column('supporting_documents', sa.Column('description', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supporting_documents', 'description')
    op.drop_constraint('uq_source_upload_id', 'audio_queue', type_='unique')
    op.alter_column('audio_queue', 'uploaded_by_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audio_queue', 'note')
    op.drop_column('audio_queue', 'artist')
    op.drop_column('audio_queue', 'title')
    op.drop_column('audio_queue', 'source_upload_id')
    op.drop_column('audio_queue', 'source')
    # ### end Alembic commands ###
