"""add_ap_ingestion_fields

Revision ID: 14a7f3f2e38c
Revises: 0001
Create Date: 2026-08-18 01:51:43.088128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a7f3f2e38c'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_queue', sa.Column('source', sa.String(), nullable=True))
    op.add_column('audio_queue', sa.Column('source_upload_id', sa.String(), nullable=True))
    op.add_column('audio_queue', sa.Column('title', sa.String(), nullable=True))
    op.add_column('audio_queue', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('audio_queue', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('audio_queue', 'uploaded_by_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_source_upload_id', 'audio_queue', ['source', 'source_upload_id'])
    op.add_column('supporting_documents', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supporting_documents', 'description')
    op.drop_constraint('uq_source_upload_id', 'audio_queue', type_='unique')
    op.alter_column('audio_queue', 'uploaded_by_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audio_queue', 'note')
    op.drop_column('audio_queue', 'artist')
    op.drop_column('audio_queue', 'title')
    op.drop_column('audio_queue', 'source_upload_id')
    op.drop_column('audio_queue', 'source')
    # ### end Alembic commands ###
