"""add storage_provider

Revision ID: 3b7d526ce95d
Revises: 14a7f3f2e38c
Create Date: 2026-08-19 00:21:04.567490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7d526ce95d'
down_revision: Union[str, Sequence[str], None] = '14a7f3f2e38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_queue', sa.Column('storage_provider', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('storage_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'storage_provider')
    op.drop_column('audio_queue', 'storage_provider')
    # ### end Alembic commands ###
