"""remove_storage_provider

Revision ID: 80466bf63a06
Revises: 3b7d526ce95d
Create Date: 2026-08-19 00:51:30.739664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80466bf63a06'
down_revision: Union[str, Sequence[str], None] = '3b7d526ce95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_queue') as batch_op:
        batch_op.drop_column('storage_provider')
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.drop_column('storage_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.add_column(sa.Column('storage_provider', sa.VARCHAR(), nullable=True))
    with op.batch_alter_table('audio_queue') as batch_op:
        batch_op.add_column(sa.Column('storage_provider', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
